name: Deploy to Staging

on:
  push:
    branches: [dev]
  workflow_dispatch:
    inputs:
      force_merge:
        description: 'Force merge even if checks fail'
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  promote-to-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Wait for CI checks to complete
      - name: Wait for lint
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'lint'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Wait for tests
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Create or update PR dev → staging
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: promote dev → staging'
          title: 'Automated promotion of dev → staging'
          body: |
            This PR was opened automatically after CI passed on dev.
          base: staging
          head: dev
          merge: ${{ github.event.inputs.force_merge == 'true' || github.event.workflow_run_conclusion == 'success' }}
