name: E2E Tests

on:
  push:
    branches:
      - main
      - next
    paths:
      - 'src/**'
      - 'tests/e2e/**'
      - 'playwright.config.ts'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/e2e/**'
      - 'playwright.config.ts'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e_tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        project: ['chromium', 'firefox', 'webkit', 'Mobile Chrome', 'Mobile Safari']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps ${{ matrix.project == 'chromium' && 'chromium' || matrix.project == 'firefox' && 'firefox' || matrix.project == 'webkit' && 'webkit' || matrix.project == 'Mobile Chrome' && 'chromium' || 'webkit' }}

      - name: Run Playwright tests
        run: pnpm exec playwright test --project="${{ matrix.project }}"
        env:
          CI: true
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 30
